version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: NServiceBus.Serilog
    versions:
    - 7.10.0
    - 7.11.0
    - 7.11.1
  - dependency-name: Serilog.Extensions.Hosting
    versions:
    - 3.1.0
    - 4.0.0
    - 4.1.0
    - 4.1.1
  - dependency-name: NServiceBus.Transport.AzureServiceBus
    versions:
    - 1.8.0
  - dependency-name: Microsoft.ApplicationInsights.WorkerService
    versions:
    - 2.16.0
  - dependency-name: NServiceBus
    versions:
    - 7.4.4
