pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: PowerShell@2
    displayName: 'Build Script'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Nuget Packages to Artifacts'
    inputs:
      PathtoPublish: 'artifacts'